version: '3.4'

services:
  eta:    
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Expense-Tracking-Application
    ports:
     - "8080:8080"
     - "8081:8081"
    depends_on:
     - sqlserver
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
    networks:
     - expensenetwork
    restart: on-failure

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Pass@123"
      ACCEPT_EULA: "Y"
    ports:
     - "1433:1433"
    volumes:
     - sqlvolume:/var/opt/mssql
    networks:
     - expensenetwork

networks:
  expensenetwork:
 
volumes:
  sqlvolume:
